export const comman = {
    // App branding
    EN: "EN",
    SafeNet: "Safe Net",
    SecureMonitoring: "Secure Monitoring",
    Version: "v2.0",
    
    // Navigation
    Dashboard: "Dashboard",
    Health: "Health",
    Logout: "Logout",
    Todo: "Todo",
    MenstruationCycle: "Menstruation Cycle",
    QuickActions: "Quick Actions",
    Notifications: "Notifications",
    Profile: "Profile",

    // Authentication
    WelcomeBack: "Welcome Back",
    AccessSecureDashboard: "Access your secure dashboard",
    CreateAccount: "Create Account",
    JoinSafeNet: "Join Safe Net for secure monitoring",
    SignIn: "Sign in",
    SigningIn: "Signing in...",
    CreatingAccount: "Creating account...",
    
    // Form labels
    EmailAddress: "Email Address",
    Password: "Password",
    FullName: "Full Name",
    ConfirmPassword: "Confirm Password",
    
    // Form placeholders
    EmailPlaceholder: "your@email.com",
    PasswordPlaceholder: "••••••••",
    NamePlaceholder: "John Doe",
    EnterEmail: "Enter your email",
    EnterNewPassword: "Enter new password",
    ConfirmNewPassword: "Confirm new password",
    
    // Form actions
    RememberMe: "Remember me",
    ForgotPassword: "Forgot password?",
    DontHaveAccount: "Don't have an account?",
    GetStarted: "Get started",
    AlreadyHaveAccount: "Already have an account?",
    SignInHere: "Sign in here",
    
    // Terms and conditions
    AgreeToTerms: "I agree to the",
    TermsOfService: "Terms of Service",
    And: "and",
    PrivacyPolicy: "Privacy Policy",
    
    // Page titles and headers
    TodoList: "Todo List",
    ManageTasks: "Manage your tasks and stay organized",
    HealthTracker: "Health Tracker",
    MonitorHealth: "Monitor your health and wellness",
    CycleTracker: "Cycle Tracker",
    TrackCycle: "Track your menstrual cycle and health",
    WelcomeBackUser: "Welcome back",
    WhatsHappening: "Here's what's happening with your children today.",
    
    // Todo page
    AddNewTask: "Add New Task",
    TaskTitle: "Task Title",
    Priority: "Priority",
    DueDate: "Due Date",
    LowPriority: "Low Priority",
    MediumPriority: "Medium Priority",
    HighPriority: "High Priority",
    AddTask: "Add Task",
    EditTask: "Edit Task",
    UpdateTask: "Update Task",
    DeleteTask: "Delete Task",
    CompleteTask: "Complete Task",
    MarkComplete: "Mark Complete",
    MarkIncomplete: "Mark Incomplete",
    NoTasks: "No tasks yet. Add your first task to get started!",
    AllTasks: "All Tasks",
    CompletedTasks: "Completed Tasks",
    PendingTasks: "Pending Tasks",
    
    // Health page
    Vitals: "Vitals",
    Symptoms: "Symptoms",
    Medications: "Medications",
    HealthGoals: "Health Goals",
    AddVital: "Add Vital",
    AddSymptom: "Add Symptom",
    AddMedication: "Add Medication",
    AddGoal: "Add Goal",
    BloodPressure: "Blood Pressure",
    HeartRate: "Heart Rate",
    Temperature: "Temperature",
    Weight: "Weight",
    Headache: "Headache",
    Fatigue: "Fatigue",
    VitaminD: "Vitamin D",
    IronSupplement: "Iron Supplement",
    ExerciseDaily: "Exercise 30 minutes daily",
    DrinkWater: "Drink 8 glasses of water",
    SleepHours: "Sleep 8 hours",
    Normal: "normal",
    Mild: "mild",
    Moderate: "moderate",
    Severe: "severe",
    Daily: "Daily",
    Morning: "Morning",
    Evening: "Evening",
    Taken: "Taken",
    NotTaken: "Not Taken",
    healthStats:"Health Stats",
    healthNote:"Note: in order to reduce the clutter of data nodes, the data is downsampled.",

    
    // Menstruation page
    CycleLength: "Cycle Length",
    LastPeriod: "Last Period",
    NextPeriod: "Next Period",
    CurrentPhase: "Current Phase",
    CycleDay: "Cycle Day",
    AddMood: "Add Mood",
    MoodTracking: "Mood Tracking",
    Cramps: "Cramps",
    MoodSwings: "Mood swings",
    Happy: "happy",
    Irritable: "irritable",
    Tired: "tired",
    Follicular: "follicular",
    Luteal: "luteal",
    Menstrual: "menstrual",
    Ovulatory: "ovulatory",
    DaysAverage: " days average",
    Predicted: "Predicted",
    FertilityWindow: "Fertility Window",
    PeriodDays: "Period Days",
    Today: "Today",
    PredictionSettings: "Period Predictions Settings",
    UpdateDetails: "Update Details",
    CycleCalendar: "Cycle Calendar",


    //Profile page
    ProfileDes:"Here’s what’s happened today.",
    AddChildwithPlus:"+ Add Child",
    AddChild:"Add Child",
    AddChildDes:"Fill in the details to add a new child.",
    Gender:"Gender",
    Male:"Male",
    Female:"Female",
    RecentAlerts:"Recent Alerts",
    NoDevice:"No Available Device",
    YearsOld:" years old",
    EditChild:"Edit Child",
    EditChildDes:"Edit the details.",
    
    // Common actions
    Add: "Add",
    Edit: "Edit",
    Delete: "Delete",
    Save: "Save",
    Cancel: "Cancel",
    Update: "Update",
    Submit: "Submit",
    Loading: "Loading...",
    
    // Status messages
    LoggedOutSuccessfully: "Logged out successfully!",
    TaskAdded: "Task added successfully!",
    TaskUpdated: "Task updated successfully!",
    TaskDeleted: "Task deleted successfully!",
    VitalAdded: "Vital added successfully!",
    SymptomAdded: "Symptom added successfully!",
    MedicationAdded: "Medication added successfully!",
    GoalAdded: "Goal added successfully!",
    
    // Footer
    Copyright: "© Safe Net. All rights reserved.",
    
    // User interface
    User: "User",
    Settings: "Settings",
    Search: "Search",
    Filter: "Filter",
    Sort: "Sort",
    View: "View",
    Details: "Details",
    Close: "Close",
    Back: "Back",
    Next: "Next",
    Previous: "Previous",
    First: "First",
    Last: "Last",
    Page: "Page",
    Of: "of",
    Items: "items",
    Showing: "Showing",
    To: "to",
    Results: "results",
    NoResults: "No results found",
    Error: "Error",
    Success: "Success",
    Warning: "Warning",
    Info: "Information",
    Confirm: "Confirm",
    Yes: "Yes",
    No: "No",
    Ok: "OK",


    lowbattery:'Low Battery',
    hightemp:'High temperature detected '
}